#!/usr/bin/env bash
# .devcontainer/setup.sh
#
# Runs once after the Codespace container is created (postCreateCommand).
#
# 1. Writes a .env file from Codespace secrets (injected as environment
#    variables by devcontainer.json → remoteEnv).
# 2. Builds and starts the full docker compose stack.
#
# Secrets are injected by GitHub Codespaces from the secrets you configured at:
#   github.com → Settings → Codespaces → Secrets
# Each secret must be scoped to this repository.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

echo "──────────────────────────────────────────────────────────────"
echo " NoSwipeChat – Codespace setup"
echo "──────────────────────────────────────────────────────────────"

# ── 1. Write .env from Codespace secrets ─────────────────────────────────────
# Each variable falls back to a placeholder if the secret is not yet set so the
# stack can still start (you can update .env and restart compose later).
if [ -f "$ENV_FILE" ]; then
  echo "ℹ  .env already exists – skipping generation (delete it to regenerate)."
else
  echo "✎  Writing $ENV_FILE from Codespace secrets…"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by .devcontainer/setup.sh – DO NOT COMMIT
# Re-run .devcontainer/setup.sh or delete this file to regenerate.

JWT_SECRET=${JWT_SECRET:-change_me_set_JWT_SECRET_in_codespace_secrets}

FACEBOOK_APP_ID=${FACEBOOK_APP_ID:-}
FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET:-}
EXPO_PUBLIC_FACEBOOK_APP_ID=${FACEBOOK_APP_ID:-}

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}

LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID:-}
LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET:-}
EOF
  echo "   done."
fi

# ── 2. Build and start the stack ──────────────────────────────────────────────
echo ""
echo "🐳  Building and starting docker compose stack…"
cd "$REPO_ROOT"
docker compose -f docker-compose.yml up -d --build

echo ""
echo "✅  Stack is starting.  Access the app at:"
echo "    http://localhost:8080           (local)"
if [ -n "${CODESPACE_NAME:-}" ]; then
  echo "    https://${CODESPACE_NAME}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-preview.app.github.dev}  (Codespace)"
fi
echo ""
echo "Run 'docker compose -f docker-compose.yml ps' to check service health."
